# Generates the variable-identity corpus: every binding shape crossed with every read shape in each context, and
# for each fixture a golden that says, per variable occurrence, which binding it belongs to. The compiler is the
# oracle: it gives each variable occurrence a version, and two occurrences are the same binding exactly when the
# versions agree. A rebinding, which the plugin renames as one variable with what it rebinds, is chained to the
# version a read placed just before it resolves to, which the compiler is asked with a probe.
#
# Run from this directory: `mise exec -- elixir generate.exs`. Elixir is needed only here, never by the tests.

defmodule Oracle do
  @name "x"

  # Every written file starts with this, so the header's lines are part of what the compiler sees and numbers.
  @header [
    "# Generated by generate.exs beside the cases directory; do not edit.",
    "# Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/model/psi/variable/oracle."
  ]

  # Each binder is {id, kind, lines}. `:assign` binds in a match and chains to what it rebinds; `:pattern` binds
  # afresh; `:branch` is an assignment in a branch body that chains but does not leak. `list`, `c`, `m` and `key`
  # are bound by the context.
  def binders do
    [
      {"match", :assign, ["x = 1"]},
      {"match_tuple", :assign, ["{x, _} = {1, 2}"]},
      {"match_list_head", :assign, ["[x | _] = [1, 2]"]},
      {"match_list", :assign, ["[x] = [1]"]},
      {"match_map", :assign, ["%{k: x} = %{k: 1}"]},
      {"match_map_key", :assign, ["%{^key => x} = %{key => 1}"]},
      {"match_bitstring", :assign, ["<<x::8>> = <<1>>"]},
      {"match_ok", :assign, ["{:ok, x} = {:ok, 1}"]},
      {"match_nested", :assign, ["{:ok, [%{k: x}]} = {:ok, [%{k: 1}]}"]},
      {"match_in_tuple", :assign, ["t = {x = 1, 2}"]},
      {"match_in_list", :assign, ["l = [x = 1]"]},
      {"match_in_map", :assign, ["m2 = %{k: x = 1}"]},
      {"match_in_map_update", :assign, ["m2 = %{m | k: x = 1}"]},
      {"match_in_interpolation", :assign, ["s = \"\#{x = 1}\""]},
      {"match_in_call", :assign, ["y = IO.inspect(x = 1)"]},
      {"match_in_keyword", :assign, ["y = IO.inspect(1, label: x = \"l\")"]},
      {"match_in_bracket", :assign, ["y = m[x = :k]"]},
      {"match_in_binary_op", :assign, ["y = (x = 1) + 1"]},
      {"match_in_pipe", :assign, ["y = (x = 1) |> Integer.to_string()"]},
      {"match_case", :assign, ["x = case c do", "  v -> v", "end"]},
      {"case_clause", :pattern, ["case c do", "  x -> x", "  _ -> nil", "end"]},
      {"case_clause_tuple", :pattern, ["case c do", "  {x, _} -> x", "  _ -> nil", "end"]},
      {"case_clause_guard", :pattern, ["case c do", "  x when x > 0 -> x", "  _ -> nil", "end"]},
      {"fn_param", :pattern, ["f = fn x -> x end", "f.(1)"]},
      {"fn_param_guard", :pattern, ["f = fn x when x > 0 -> x end", "f.(1)"]},
      {"fn_param_tuple", :pattern, ["f = fn {x, _} -> x end", "f.({1, 2})"]},
      {"for_generator", :pattern, ["for x <- list, do: x"]},
      {"for_generator_filter", :pattern, ["for x <- list, x > 0, do: x"]},
      {"for_generator_block", :pattern, ["for x <- list do", "  x", "end"]},
      {"with_generator", :pattern, ["with {:ok, x} <- c do", "  x", "end"]},
      {"with_generator_else", :pattern, ["with {:ok, x} <- c do", "  x", "else", "  _ -> nil", "end"]},
      {"receive_clause", :pattern, ["receive do", "  {:msg, x} -> x", "after", "  0 -> nil", "end"]},
      {"rescue_in", :pattern, ["try do", "  raise \"boom\"", "rescue", "  x in RuntimeError -> x", "end"]},
      {"if_branch", :branch, ["if c do", "  x = 1", "end"]},
      {"unless_branch", :branch, ["unless c do", "  x = 1", "end"]},
      {"cond_branch", :branch, ["cond do", "  c -> x = 1", "  true -> nil", "end"]},
      {"case_body", :branch, ["case c do", "  _ -> x = 1", "end"]},
      {"fn_body", :branch, ["f = fn _e -> x = 1 end", "f.(1)"]},
      {"cond_fn_param", :pattern, ["h = cond do", "  c -> fn x -> x end", "  true -> nil", "end"]},
      {"case_fn_param", :pattern, ["case c do", "  _ -> fn x -> x end", "end"]},
      {"try_body", :branch, ["try do", "  x = 1", "after", "  nil", "end"]}
    ]
  end

  # Each read is {id, lines}.
  def reads do
    [
      {"bare", ["x"]},
      {"call_argument", ["IO.inspect(x)"]},
      {"right_of_match", ["y = x"]},
      {"in_tuple", ["y = {x, 2}"]},
      {"in_list", ["y = [x]"]},
      {"in_map", ["y = %{k: x}"]},
      {"in_map_update", ["y = %{m | k: x}"]},
      {"in_interpolation", ["y = \"\#{x}\""]},
      {"in_binary_op", ["y = x + 1"]},
      {"in_bracket", ["y = m[x]"]},
      {"in_keyword", ["IO.inspect(1, label: x)"]},
      {"in_closure", ["Enum.map(list, fn _e -> x end)"]},
      {"in_case_body", ["case c do", "  _ -> x", "end"]},
      {"in_case_guard", ["case c do", "  z when z > x -> z", "  _ -> nil", "end"]},
      {"in_case_pin", ["case c do", "  ^x -> :same", "  _ -> :other", "end"]},
      {"in_if_body", ["if c do", "  x", "end"]},
      {"in_if_condition", ["if x do", "  nil", "end"]},
      {"pin_match", ["^x = 1"]},
      {"in_for_body", ["for e <- list, do: e + x"]},
      {"in_for_filter", ["for e <- list, e > x, do: e"]},
      {"in_with_body", ["with {:ok, w} <- c do", "  {w, x}", "end"]},
      {"in_string_concat", ["y = \"a\" <> x"]},
      {"after_rebinding", ["x = x + 1", "x"]},
      {"in_pipe", ["y = x |> IO.inspect()"]},
      {"in_capture", ["f = &IO.inspect(x, &1)", "f.(1)"]},
      {"in_anonymous_call", ["y = c.(x)"]}
    ]
  end

  # Each context is {id, extension, wrapper, lines the wrapper puts before the body}.
  def contexts do
    [
      {"top", ".exs", &top_wrap/1, 4},
      {"def", ".ex", &def_wrap/1, 2},
      {"fn", ".ex", &fn_wrap/1, 3}
    ]
  end

  defp top_wrap(body) do
    ["c = {:ok, 1}", "list = [1, 2]", "m = %{k: 1}", "key = :k"] ++ body
  end

  defp def_wrap(body) do
    ["defmodule Fixture do", "  def run(c, list, m, key) do"] ++ indent(body, 4) ++ ["  end", "end"]
  end

  defp fn_wrap(body) do
    ["defmodule Fixture do", "  def run(c, list, m, key) do", "    Enum.map(list, fn _e ->"] ++
      indent(body, 6) ++ ["    end)", "  end", "end"]
  end

  defp indent(lines, n), do: Enum.map(lines, fn "" -> ""; line -> String.duplicate(" ", n) <> line end)

  # A read after a pattern binder or a branch binder cannot see it, so those get an outer `x = 0` first: the read
  # then resolves to the outer binding, and a branch assignment chains to it. Each fixture is
  # {id, extension, lines, lines of the binder that bind afresh}.
  def fixtures do
    for {context_id, extension, wrap, prefix} <- contexts(),
        {binder_id, kind, binder_lines} <- binders(),
        {read_id, read_lines} <- reads() do
      outer = if kind == :assign, do: [], else: ["x = 0"]
      body = outer ++ binder_lines ++ read_lines
      binder_start = prefix + length(outer) + 1
      pattern_lines = if kind == :pattern, do: Enum.to_list(binder_start..(binder_start + length(binder_lines) - 1)), else: []
      {"#{context_id}__#{binder_id}__#{read_id}", extension, wrap.(body), pattern_lines}
    end
  end

  # Occurrences with a column, as {name, line, column, version}.
  def occurrences(source, extension) do
    {result, _warnings} = with_silenced_stderr(fn -> occurrences!(source, extension) end)
    result
  rescue
    e -> {:error, Exception.message(e)}
  end

  defp with_silenced_stderr(fun) do
    {:ok, device} = StringIO.open("")
    previous = Process.group_leader()
    original_stderr = Process.whereis(:standard_error)
    Process.unregister(:standard_error)
    Process.register(device, :standard_error)

    try do
      {fun.(), ""}
    after
      Process.unregister(:standard_error)
      Process.register(original_stderr, :standard_error)
      Process.group_leader(self(), previous)
      StringIO.close(device)
    end
  end

  defp occurrences!(source, extension) do
    Code.put_compiler_option(:parser_options, columns: true)
    Code.put_compiler_option(:debug_info, true)
    Code.put_compiler_option(:ignore_module_conflict, true)

    quoted =
      case extension do
        ".exs" ->
          {:ok, quoted} = Code.string_to_quoted(source, columns: true)
          env = :elixir_env.new()
          {expanded, _, _} = :elixir_expand.expand(quoted, :elixir_env.env_to_ex(env), env)
          expanded

        ".ex" ->
          [{Fixture, beam}] = Code.compile_string(source, "fixture.ex")

          {:ok, {_, [debug_info: {:debug_info_v1, :elixir_erl, {:elixir_v1, map, _}}]}} =
            :beam_lib.chunks(beam, [:debug_info])

          for {_, _kind, _meta, clauses} <- map.definitions, {_meta, args, guards, body} <- clauses do
            [args, guards, body]
          end
      end

    {_, vars} =
      Macro.prewalk(quoted, [], fn
        {v, meta, ctx} = node, acc when is_atom(v) and is_atom(ctx) and v != :_ ->
          case {meta[:column], meta[:version]} do
            {nil, _} -> {node, acc}
            {_, nil} -> {node, acc}
            {col, version} -> {node, [{Atom.to_string(v), meta[:line], col, version} | acc]}
          end

        node, acc ->
          {node, acc}
      end)

    vars
    |> Enum.reject(fn {name, _, _, _} -> String.starts_with?(name, "_") end)
    |> Enum.uniq()
    |> Enum.sort_by(fn {_, line, col, _} -> {line, col} end)
  end

  # The version a read of `name` placed just before the binding on `line` resolves to, or nil when nothing binds
  # it there.
  # A binding in an inline clause body, `_ -> x = 1`, gets the read inside the body, after the `->`.
  def probe(lines, extension, name, line) do
    {before, [text | rest]} = Enum.split(lines, line - 1)

    {probe_line, column} =
      case String.split(text, "-> ", parts: 2) do
        [head, tail] -> {head <> "-> " <> name <> "; " <> tail, String.length(head) + 4}
        _ -> {String.duplicate(" ", String.length(text) - String.length(String.trim_leading(text))) <> name, nil}
      end

    probe_lines = if column, do: before ++ [probe_line | rest], else: before ++ [probe_line, text | rest]

    case occurrences(Enum.join(probe_lines, "\n") <> "\n", extension) do
      {:error, _} ->
        nil

      occurrences ->
        Enum.find_value(occurrences, fn {n, l, c, v} ->
          if n == name and l == line and (column == nil or c == column), do: v
        end)
    end
  end

  # Chains each assignment binding of `x` to what it rebinds: union-find over versions keyed by the root version.
  # A binding on a pattern line, a clause pattern, parameter, generator or `rescue`, binds afresh and is a root.
  def classes(lines, extension, occurrences, pattern_lines) do
    bindings =
      occurrences
      |> Enum.group_by(fn {_, _, _, v} -> v end)
      |> Enum.map(fn {v, [{name, line, _, _} | _]} -> {v, name, line} end)

    parents =
      for {v, name, line} <- bindings, line not in pattern_lines, line > length(@header), into: %{} do
        {v, probe(lines, extension, name, line)}
      end

    versions = occurrences |> Enum.map(fn {_, _, _, v} -> v end) |> Enum.uniq()
    Map.new(versions, fn v -> {v, root(v, parents)} end)
  end

  defp root(v, parents) do
    case Map.get(parents, v) do
      nil -> v
      ^v -> v
      parent -> root(parent, parents)
    end
  end

  def golden(occurrences, classes) do
    x_versions = occurrences |> Enum.filter(fn {n, _, _, _} -> n == @name end) |> Enum.map(fn {_, _, _, v} -> v end)
    first_of = occurrences |> Enum.reverse() |> Map.new(fn {_, l, c, v} -> {v, {l, c}} end)

    for {name, line, col, version} <- occurrences do
      class = Map.fetch!(classes, version)
      kind = if first_of[version] == {line, col}, do: "bind", else: "read"
      "#{name} #{line} #{col} #{version} #{class} #{kind}"
    end
    |> Enum.concat(["# x versions: #{Enum.uniq(x_versions) |> Enum.join(",")}"])
  end

  def run do
    File.rm_rf!("cases")
    File.mkdir_p!("cases")
    fixtures = fixtures()
    {written, skipped} =
      Enum.reduce(fixtures, {0, []}, fn {id, extension, lines, pattern_lines}, {written, skipped} ->
        lines = @header ++ lines
        pattern_lines = Enum.map(pattern_lines, &(&1 + length(@header)))
        source = Enum.join(lines, "\n") <> "\n"

        case occurrences(source, extension) do
          {:error, message} ->
            {written, [{id, message} | skipped]}

          occurrences ->
            classes = classes(lines, extension, occurrences, pattern_lines)
            File.write!("cases/#{id}#{extension}", source)
            golden = @header ++ golden(occurrences, classes)
            File.write!("cases/#{id}.golden", Enum.join(golden, "\n") <> "\n")
            {written + 1, skipped}
        end
      end)

    IO.puts("written #{written}, skipped #{length(skipped)}")
    for {id, message} <- Enum.reverse(skipped), do: IO.puts("  skipped #{id}: #{message |> String.split("\n") |> hd()}")
  end
end

Oracle.run()
