name: 'Setup Build Environment'
description: 'Sets up Java, Elixir, and Gradle for IntelliJ plugin builds'

# Note, can't do type hinting in composite actions yet...
inputs:
  elixir-version:
    description: 'Elixir version'
    required: false
    default: '1.13.4'
  otp-version:
    description: 'OTP version'
    required: false
    default: '24.3.4.6'
  idea-version:
    description: 'IntelliJ IDEA version to test against. Keep in sync with matrix-setup in shared-test.yml'
    required: false
    default: '253.28294.334'  # 2025.3 - should match first version in shared-test.yml
  skip-jcef:
    description: 'Skip JCEF package (set to true for release/verifyPlugin jobs). Default is false.'
    required: false
    default: 'false'
  gradle-cache-read-only:
    description: 'Use read-only Gradle cache (for non-main branches or matrix jobs). Default is true.'
    required: false
    default: 'true'
  github-token:
    description: 'GitHub token for API access (required for setup-java to download JBR)'
    required: true

runs:
  using: composite
  steps:
    - name: Free Disk Space
      id: free-disk-space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
          tool-cache: false
          large-packages: false

    - name: Cache JetBrains JDK
      id: cache-jdk
      uses: actions/cache@v4
      with:
        path: /opt/hostedtoolcache/Java_JetBrains_*
        key: jdk-${{ runner.os }}-${{ runner.arch }}-jetbrains-21-${{ inputs.skip-jcef == 'false' && 'jcef' || 'nojcef' }}

    - name: Setup JBR 21
      id: setup-java
      uses: actions/setup-java@v5
      with:
        distribution: 'jetbrains'
        java-version: 21
        java-package: ${{ inputs.skip-jcef == 'false' && 'jdk+jcef' || 'jdk' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Setup Gradle
      id: setup-gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-read-only: ${{ inputs.gradle-cache-read-only == 'true' }}
        cache-overwrite-existing: false
        gradle-home-cache-cleanup: true
        add-job-summary-as-pr-comment: 'on-failure'
#        # Exclude IntelliJ IDE downloads and extractions from cache (~10GB)
#        # These are fast to re-download and would bloat the cache
#        gradle-home-cache-excludes: |
#          caches/modules-2/files-2.1/idea
#          caches/*/transforms
        build-scan-publish: true
        build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
        build-scan-terms-of-use-agree: 'yes'

    - name: Restore Elixir cache
      id: cache-elixir-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          cache/elixir-${{ inputs.elixir-version }}-intellij_elixir-2.1.0/_build
          cache/elixir-${{ inputs.elixir-version }}-intellij_elixir-2.1.0/deps
        key: elixir-${{ runner.os }}-${{ runner.arch }}-${{ inputs.elixir-version }}-otp-${{ inputs.otp-version }}-quoter-${{ hashFiles('gradle.properties') }}
        restore-keys: |
          elixir-${{ runner.os }}-${{ runner.arch }}-${{ inputs.elixir-version }}-otp-${{ inputs.otp-version }}-

    - name: Setup Elixir
      id: setup-elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.otp-version }}
        elixir-version: ${{ inputs.elixir-version }}

    - name: Export Environment Variables
      id: export-environment-variables
      shell: bash
      run: |
        if [ -n "${{ inputs.elixir-version }}" ]; then
          echo "OTP_RELEASE=${{ inputs.otp-version }}" >> $GITHUB_ENV
          echo "ERLANG_SDK_HOME=$(erl -eval 'io:format("~s", [code:root_dir()]).' -noshell -run init stop)" >> $GITHUB_ENV
        fi
        chmod +x gradlew
        if [ -n "${{ inputs.idea-version }}" ]; then
          echo "ORG_GRADLE_PROJECT_ideaVersion=${{ inputs.idea-version }}" >> $GITHUB_ENV
        fi

    - name: Save Elixir cache
      id: cache-elixir-save
      if: always() && inputs.gradle-cache-read-only != 'true' && steps.cache-elixir-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          cache/elixir-${{ inputs.elixir-version }}-intellij_elixir-2.1.0/_build
          cache/elixir-${{ inputs.elixir-version }}-intellij_elixir-2.1.0/deps
          !cache/**/tmp/pipe/**
          !cache/**/distillery/priv
        key: ${{ steps.cache-elixir-restore.outputs.cache-primary-key }}
