name: 'Setup Build Environment'
description: 'Sets up Java, Elixir, and Gradle for IntelliJ plugin builds'

# Note, can't do type hinting in composite actions yet...
inputs:
  elixir-version:
    description: 'Elixir version'
    required: false
    default: '1.13.4'
  otp-version:
    description: 'OTP version'
    required: false
    default: '24.3.4.6'
  idea-version:
    description: 'IntelliJ IDEA version to test against. Keep in sync with matrix-setup in shared-test.yml'
    required: false
    default: '253.28294.334'  # 2025.3 - should match first version in shared-test.yml
  gradle-cache-read-only:
    description: 'Use read-only Gradle cache (for non-main branches or matrix jobs). Default is true.'
    required: false
    default: 'true'
  github-token:
    description: 'GitHub token for API access (required for setup-java to download JBR)'
    required: true
  build-scan-publish:
    description: 'Whether to publish Gradle build scans'
    required: false
    default: 'false'
  setup-elixir:
    description: 'If true, will setup the Elixir environment, restore and cache Elixir build artifacts. Not needed for the verify-plugin job.'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Free Disk Space
      id: free-disk-space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        large-packages: false

    - name: Cache JetBrains JDK
      id: cache-jdk
      uses: actions/cache@v5
      with:
        path: /opt/hostedtoolcache/Java_JetBrains_*
        key: jdk-${{ runner.os }}-${{ runner.arch }}-jetbrains-21

    - name: Setup JBR 21
      id: setup-java
      uses: actions/setup-java@v5
      with:
        distribution: 'jetbrains'
        java-version: 21
        java-package: 'jdk'
        token: ${{ inputs.github-token }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    # This sets project properties, allowing us to override gradle.properties via environment variables,
    # applying to all Gradle tasks. Means we don't need to do like `./gradlew -PplatformVersion=xxx`
    # Needed because we can't just use env, as we're in a composite action, and env set here won't propagate to
    # later steps in the workflow that use this action.
    # https://docs.gradle.org/current/userguide/build_environment.html#setting_a_project_property
    - name: Export Environment Variables
      id: export-environment-variables
      shell: bash
      run: |
        if [ -n "${{ inputs.idea-version }}" ]; then
          echo "ORG_GRADLE_PROJECT_platformVersion=${{ inputs.idea-version }}" >> $GITHUB_ENV
          export ORG_GRADLE_PROJECT_platformVersion=${{ inputs.idea-version }}
        fi
        echo "ORG_GRADLE_PROJECT_skipSearchableOptions=false" >> $GITHUB_ENV
        export ORG_GRADLE_PROJECT_skipSearchableOptions=false

    - name: Setup Gradle
      id: setup-gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-read-only: true
        add-job-summary-as-pr-comment: 'on-failure'
        build-scan-publish: ${{ inputs.build-scan-publish }}
        build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
        build-scan-terms-of-use-agree: 'yes'
        github-token: ${{ inputs.github-token }}

    - name: Restore Elixir cache
      id: cache-elixir-restore
      if: ${{ inputs.setup-elixir == 'true' }}
      uses: actions/cache/restore@v5
      with:
        path: |
          cache/elixir-${{ inputs.elixir-version }}-intellij_elixir-2.1.0/_build
          cache/elixir-${{ inputs.elixir-version }}-intellij_elixir-2.1.0/deps
        key: elixir-${{ runner.os }}-${{ runner.arch }}-${{ inputs.elixir-version }}-otp-${{ inputs.otp-version }}-quoter-${{ hashFiles('gradle.properties') }}
        restore-keys: |
          elixir-${{ runner.os }}-${{ runner.arch }}-${{ inputs.elixir-version }}-otp-${{ inputs.otp-version }}-

    - name: Setup Elixir
      id: setup-elixir
      if: ${{ inputs.setup-elixir == 'true' }}
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.otp-version }}
        elixir-version: ${{ inputs.elixir-version }}

    - name: Export Elixir Environment Variables
      id: export-elixir-environment-variables
      if: ${{ inputs.setup-elixir == 'true' && inputs.elixir-version != '' }}
      shell: bash
      run: |
        echo "OTP_RELEASE=${{ inputs.otp-version }}" >> $GITHUB_ENV
        echo "ERLANG_SDK_HOME=$(erl -eval 'io:format("~s", [code:root_dir()]).' -noshell -run init stop)" >> $GITHUB_ENV

    - name: Save Elixir cache
      id: cache-elixir-save
      if: always() && inputs.gradle-cache-read-only != 'true' && steps.cache-elixir-restore.outputs.cache-hit != 'true' && inputs.setup-elixir == 'true'
      uses: actions/cache/save@v5
      with:
        path: |
          cache/elixir-${{ inputs.elixir-version }}-intellij_elixir-2.1.0/_build
          cache/elixir-${{ inputs.elixir-version }}-intellij_elixir-2.1.0/deps
          !cache/**/tmp/pipe/**
          !cache/**/distillery/priv
        key: ${{ steps.cache-elixir-restore.outputs.cache-primary-key }}
