# Generated by generate.exs beside the cases directory; do not edit.
# Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/model/psi/variable/oracle.
defmodule Fixture do
  def run(c, list, m, key) do
    x = case c do
      v -> v
    end
    with {:ok, w} <- c do
      {w, x}
    end
  end
end
