# Generated by generate.exs beside the cases directory; do not edit.
# Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/model/psi/variable/oracle.
defmodule Fixture do
  def run(c, list, m, key) do
    y = (x = 1) |> Integer.to_string()
    f = &IO.inspect(x, &1)
    f.(1)
  end
end
