# Generated by generate.exs beside the cases directory; do not edit.
# Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/model/psi/variable/oracle.
defmodule Fixture do
  def run(c, list, m, key) do
    x = 0
    if c do
      x = 1
    end
    f = &IO.inspect(x, &1)
    f.(1)
  end
end
