# Generated by generate.exs beside the cases directory; do not edit.
# Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/model/psi/variable/oracle.
defmodule Fixture do
  def run(c, list, m, key) do
    x = 0
    case c do
      x -> x
      _ -> nil
    end
    case c do
      z when z > x -> z
      _ -> nil
    end
  end
end
