# Generated by generate.exs beside the cases directory; do not edit.
# Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/model/psi/variable/oracle.
defmodule Fixture do
  def run(c, list, m, key) do
    Enum.map(list, fn _e ->
      {:ok, [%{k: x}]} = {:ok, [%{k: 1}]}
      IO.inspect(1, label: x)
    end)
  end
end
