# Generated by generate.exs beside the cases directory; do not edit.
# Regenerate with `mise exec -- elixir generate.exs` in testData/org/elixir_lang/model/psi/variable/oracle.
c = {:ok, 1}
list = [1, 2]
m = %{k: 1}
key = :k
l = [x = 1]
case c do
  ^x -> :same
  _ -> :other
end
