/* The following code was generated by JFlex 1.4.3 on 10/22/14 3:08 PM */

package org.elixir_lang;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;
import org.elixir_lang.lexer.group.*;
import org.elixir_lang.psi.ElixirTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/22/14 3:08 PM from the specification file
 * <tt>/Users/luke.imhoff/git/KronicDeth/intellij-elixir/src/org/elixir_lang/Elixir.flex</tt>
 */
public class ElixirFlexLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int GROUP_HEREDOC_END = 8;
  public static final int INTERPOLATION = 16;
  public static final int GROUP_HEREDOC_LINE_START = 12;
  public static final int SIGIL_MODIFIERS = 22;
  public static final int SIGIL = 20;
  public static final int GROUP_HEREDOC_START = 14;
  public static final int GROUP = 6;
  public static final int ATOM_START = 4;
  public static final int YYINITIAL = 0;
  public static final int GROUP_HEREDOC_LINE_BODY = 10;
  public static final int NAMED_SIGIL = 18;
  public static final int ATOM_BODY = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8, 
     9, 10, 11, 11, 12, 12, 13, 13
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\34\1\30\1\0\1\34\1\32\22\0\1\34\1\3\1\45"+
    "\1\35\1\0\1\5\1\10\1\44\1\52\1\53\1\21\1\15\1\0"+
    "\1\16\1\11\1\22\1\36\1\40\6\43\2\25\1\17\1\33\1\1"+
    "\1\4\1\2\1\24\1\23\1\27\1\37\4\27\21\51\1\41\2\51"+
    "\1\52\1\20\1\53\1\14\1\26\1\0\1\47\1\50\4\47\10\46"+
    "\1\42\10\46\1\31\2\46\1\6\1\13\1\7\1\12\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\16\0\1\1\1\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\1\2\7\1\5\1\1\1\5\1\10\1\11"+
    "\1\12\1\10\5\13\1\1\2\13\1\1\4\13\2\1"+
    "\1\13\1\14\1\1\1\15\1\16\1\17\3\16\1\0"+
    "\1\20\1\16\4\21\1\22\1\1\1\23\2\24\1\25"+
    "\1\26\1\27\1\26\2\30\1\0\1\31\6\0\1\13"+
    "\1\0\1\13\1\0\1\13\2\0\1\13\1\0\2\32"+
    "\1\33\5\0\1\30\2\31\1\7\1\0\1\32\1\34"+
    "\1\0\1\35\1\36\1\0\1\30\1\0\1\37\13\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268\0\u0268"+
    "\0\u0268\0\u0294\0\u0268\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370"+
    "\0\u039c\0\u0268\0\u03c8\0\u03f4\0\u0268\0\u0268\0\u0420\0\u044c"+
    "\0\u0478\0\u04a4\0\u04d0\0\u04fc\0\u0528\0\u0554\0\u0580\0\u05ac"+
    "\0\u05d8\0\u0604\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u0268"+
    "\0\u0268\0\u070c\0\u0268\0\u0268\0\u0268\0\u0738\0\u0764\0\u0790"+
    "\0\u07bc\0\u0268\0\u07e8\0\u0268\0\u0814\0\u0840\0\u086c\0\u0268"+
    "\0\u0898\0\u0268\0\u0268\0\u08c4\0\u0268\0\u0268\0\u0268\0\u08f0"+
    "\0\u0268\0\u091c\0\u0948\0\u0974\0\u09a0\0\u0974\0\u09cc\0\u09f8"+
    "\0\u03c8\0\u0a24\0\u0a50\0\u0a50\0\u0a7c\0\u0554\0\u0aa8\0\u0ad4"+
    "\0\u0b00\0\u0b2c\0\u0b58\0\u0268\0\u0b84\0\u0268\0\u0bb0\0\u0840"+
    "\0\u0bdc\0\u0c08\0\u0c34\0\u0c60\0\u0948\0\u09a0\0\u0268\0\u0c8c"+
    "\0\u0cb8\0\u0268\0\u0ce4\0\u0268\0\u0268\0\u0d10\0\u0d3c\0\u0d68"+
    "\0\u0268\0\u0d94\0\u0dc0\0\u0dec\0\u0e18\0\u0e44\0\u0e70\0\u0e9c"+
    "\0\u0ec8\0\u0ef4\0\u0f20\0\u0f4c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\12\17\1\20\4\17\1\21\4\17\1\22\3\17\1\23"+
    "\1\17\1\24\1\23\1\25\1\26\1\27\5\17\1\30"+
    "\1\31\20\17\1\20\4\17\1\21\4\17\1\22\3\17"+
    "\1\32\1\17\1\33\1\32\1\34\1\26\1\27\5\17"+
    "\1\30\1\31\6\17\3\35\1\36\17\35\1\37\1\36"+
    "\3\37\1\35\1\37\1\40\3\35\6\37\2\35\4\37"+
    "\2\35\1\17\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\17\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\3\60\2\17\2\61\1\17\1\61\1\62"+
    "\4\17\1\61\1\17\2\61\1\17\2\63\4\61\2\17"+
    "\2\64\1\65\4\64\1\65\3\64\1\65\4\64\1\66"+
    "\1\64\1\65\7\64\1\67\2\64\1\70\6\64\2\65"+
    "\5\64\1\65\44\0\2\71\6\0\20\64\1\66\7\64"+
    "\1\72\1\64\1\73\1\72\1\64\1\70\16\64\32\74"+
    "\1\75\1\74\1\76\7\74\2\77\6\74\30\17\1\100"+
    "\1\17\1\101\1\100\27\17\1\102\2\17\1\20\4\17"+
    "\1\21\4\17\1\22\3\17\1\23\1\17\1\24\1\23"+
    "\1\25\1\26\1\27\5\17\1\30\1\31\15\17\1\102"+
    "\2\17\1\20\4\17\1\21\4\17\1\22\3\17\1\32"+
    "\1\17\1\33\1\32\1\34\1\26\1\27\5\17\1\30"+
    "\1\31\7\17\1\103\4\17\1\103\4\17\1\103\6\17"+
    "\1\103\5\17\1\0\13\17\2\104\4\17\1\103\30\17"+
    "\1\105\1\17\1\105\1\62\4\17\1\105\1\17\2\105"+
    "\3\17\4\105\2\17\31\106\1\107\1\110\7\106\1\107"+
    "\3\106\3\107\3\106\54\0\20\111\1\112\7\111\1\0"+
    "\23\111\30\0\1\23\57\0\1\25\17\0\30\26\1\0"+
    "\1\26\1\0\21\26\31\0\1\113\4\0\1\114\1\115"+
    "\1\114\1\113\1\116\1\114\4\0\1\115\47\0\1\117"+
    "\54\0\1\120\36\0\1\32\53\0\1\32\1\0\1\121"+
    "\1\32\1\34\42\0\1\37\1\0\3\37\1\0\1\37"+
    "\4\0\6\37\2\0\4\37\32\0\1\35\24\0\1\122"+
    "\1\60\1\0\1\60\5\0\1\123\1\124\2\0\1\60"+
    "\37\0\1\124\1\0\1\60\53\0\1\125\53\0\1\125"+
    "\5\0\1\60\47\0\1\126\54\0\1\60\54\0\1\127"+
    "\54\0\1\130\44\0\1\123\7\0\1\131\43\0\1\60"+
    "\10\0\1\132\54\0\1\133\54\0\1\60\40\0\1\60"+
    "\13\0\1\60\54\0\1\60\54\0\1\60\63\0\1\17"+
    "\23\0\30\134\1\0\1\135\22\134\30\0\1\64\31\0"+
    "\1\136\111\0\2\137\36\0\1\72\53\0\1\74\57\0"+
    "\1\140\7\0\2\141\52\0\2\142\36\0\1\100\67\0"+
    "\2\143\36\0\1\106\23\0\30\111\1\0\1\144\22\111"+
    "\25\0\1\145\1\0\1\145\6\0\3\145\2\0\1\145"+
    "\3\0\2\145\41\0\1\114\1\0\1\114\2\0\1\114"+
    "\46\0\1\146\1\0\1\146\57\0\1\147\54\0\1\147"+
    "\7\0\1\60\1\124\7\0\1\60\43\0\1\60\55\0"+
    "\1\60\57\0\1\60\54\0\1\60\54\0\1\60\54\0"+
    "\1\60\54\0\1\60\45\0\1\150\16\0\1\151\1\0"+
    "\1\151\6\0\3\151\2\0\1\151\3\0\2\151\47\0"+
    "\2\152\52\0\2\153\52\0\2\154\52\0\2\155\14\0"+
    "\1\156\16\0\1\157\1\0\1\157\6\0\3\157\2\0"+
    "\1\157\3\0\2\157\30\0\1\160\1\0\1\160\6\0"+
    "\3\160\2\0\1\160\3\0\2\160\30\0\1\134\1\0"+
    "\1\134\6\0\3\134\2\0\1\134\3\0\2\134\47\0"+
    "\2\161\33\0\1\162\1\0\1\162\6\0\3\162\2\0"+
    "\1\162\3\0\2\162\30\0\1\111\1\0\1\111\6\0"+
    "\3\111\2\0\1\111\3\0\2\111\12\0\1\134\15\0"+
    "\1\163\1\0\1\163\6\0\3\163\2\0\1\163\3\0"+
    "\2\163\12\0\1\111\15\0\1\164\1\0\1\164\6\0"+
    "\3\164\2\0\1\164\3\0\2\164\12\0\1\134\15\0"+
    "\1\165\1\0\1\165\6\0\3\165\2\0\1\165\3\0"+
    "\2\165\12\0\1\111\15\0\1\166\1\0\1\166\6\0"+
    "\3\166\2\0\1\166\3\0\2\166\12\0\1\134\15\0"+
    "\1\167\1\0\1\167\6\0\3\167\2\0\1\167\3\0"+
    "\2\167\12\0\1\111\15\0\1\170\1\0\1\170\6\0"+
    "\3\170\2\0\1\170\3\0\2\170\12\0\1\134\15\0"+
    "\1\171\1\0\1\171\6\0\3\171\2\0\1\171\3\0"+
    "\2\171\12\0\1\111\15\0\1\172\1\0\1\172\6\0"+
    "\3\172\2\0\1\172\3\0\2\172\12\0\1\134\15\0"+
    "\1\173\1\0\1\173\6\0\3\173\2\0\1\173\3\0"+
    "\2\173\12\0\1\111\15\0\1\174\1\0\1\174\6\0"+
    "\3\174\2\0\1\174\3\0\2\174\12\0\1\134\53\0"+
    "\1\111\44\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3960];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\16\0\3\11\1\1\1\11\6\1\1\11\2\1\2\11"+
    "\21\1\2\11\1\1\3\11\3\1\1\0\1\11\1\1"+
    "\1\11\3\1\1\11\1\1\2\11\1\1\3\11\1\1"+
    "\1\11\1\1\1\0\1\1\6\0\1\1\1\0\1\1"+
    "\1\0\1\1\2\0\1\1\1\0\1\11\1\1\1\11"+
    "\5\0\3\1\1\11\1\0\1\1\1\11\1\0\2\11"+
    "\1\0\1\1\1\0\1\11\13\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private org.elixir_lang.lexer.Stack stack = new org.elixir_lang.lexer.Stack();

  private void startQuote(CharSequence quotePromoterCharSequence) {
    String quotePromoter = quotePromoterCharSequence.toString();
    stack.push(quotePromoter, yystate());

    if (Base.isHeredocPromoter(quotePromoter)) {
      yybegin(GROUP_HEREDOC_START);
    } else {
      yybegin(GROUP);
    }
  }

  private IElementType fragmentType() {
    return stack.fragmentType();
  }

  private void handleInState(int nextLexicalState) {
    yypushback(yylength());
    yybegin(nextLexicalState);
  }

  private boolean isTerminator(CharSequence terminator) {
    return stack.terminator().equals(terminator.toString());
  }

  private boolean isInterpolating() {
    return stack.isInterpolating();
  }

  private boolean isInterpolatingSigil(CharSequence sigilName) {
    if (sigilName.length() != 1) {
      throw new IllegalArgumentException("sigil names can only be 1 character long");
    }

    return isInterpolatingSigil(sigilName.charAt(0));
  }

  private boolean isInterpolatingSigil(char sigilName) {
    return (sigilName >= 'a' && sigilName <= 'z');
  }

  private boolean isSigil() {
    return stack.isSigil();
  }

  private void nameSigil(CharSequence sigilName) {
    stack.nameSigil(sigilName.charAt(0));
  }

  private org.elixir_lang.lexer.StackFrame pop() {
    return stack.pop();
  }

  private org.elixir_lang.lexer.group.Quote promotedQuote(CharSequence promoterCharSequence) {
    // CharSequences don't look up correctly, so convert to String, which do.
    String promoter = promoterCharSequence.toString();
    org.elixir_lang.lexer.group.Quote quote = org.elixir_lang.lexer.group.Quote.fetch(promoter);

    return quote;
  }

  private IElementType promoterType() {
    return stack.promoterType();
  }

  private void setPromoter(CharSequence promoter) {
    stack.setPromoter(promoter.toString());
  }

  private IElementType sigilNameType() {
    return stack.sigilNameType();
  }

  // public for testing
  public void pushAndBegin(int lexicalState) {
    stack.push(yystate());
    yybegin(lexicalState);
  }

  private IElementType terminatorType() {
    return stack.terminatorType();
  }


  public ElixirFlexLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ElixirFlexLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 118) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch ((zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL-1] : zzBufferL.charAt(zzMarkedPosL-1))) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = (zzBufferArrayL != null ? zzBufferArrayL[zzMarkedPosL] : zzBufferL.charAt(zzMarkedPosL)) != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 28: 
          { if (isTerminator(yytext())) {
                                      if (isSigil()) {
                                        yybegin(SIGIL_MODIFIERS);
                                        return terminatorType();
                                      } else {
                                        org.elixir_lang.lexer.StackFrame stackFrame = pop();
                                        yybegin(stackFrame.getLastLexicalState());
                                        return stackFrame.terminatorType();
                                      }
                                   } else {
                                      handleInState(GROUP_HEREDOC_LINE_BODY);
                                   }
          }
        case 32: break;
        case 18: 
          { yybegin(GROUP_HEREDOC_LINE_START);
          return ElixirTypes.EOL;
          }
        case 33: break;
        case 6: 
          { return ElixirTypes.COMMENT;
          }
        case 34: break;
        case 3: 
          { pushAndBegin(ATOM_START);
                                              return ElixirTypes.COLON;
          }
        case 35: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 36: break;
        case 9: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                   yybegin(stackFrame.getLastLexicalState());
                   return ElixirTypes.ATOM_FRAGMENT;
          }
        case 37: break;
        case 24: 
          { return ElixirTypes.CHAR_TOKEN;
          }
        case 38: break;
        case 15: 
          { if (isTerminator(yytext())) {
                         org.elixir_lang.lexer.StackFrame stackFrame = pop();
                         yybegin(stackFrame.getLastLexicalState());
                         return stackFrame.terminatorType();
                       } else {
                         return fragmentType();
                       }
          }
        case 39: break;
        case 19: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                                yybegin(stackFrame.getLastLexicalState());
                                return ElixirTypes.INTERPOLATION_END;
          }
        case 40: break;
        case 23: 
          { return ElixirTypes.SIGIL_MODIFIER;
          }
        case 41: break;
        case 20: 
          { setPromoter(yytext());
                             yybegin(GROUP);
                             return promoterType();
          }
        case 42: break;
        case 12: 
          { yybegin(ATOM_BODY);
                     return ElixirTypes.ATOM_FRAGMENT;
          }
        case 43: break;
        case 31: 
          // lookahead expression with fixed lookahead length
          yypushback(3);
          { yybegin(GROUP_HEREDOC_END);
                                                  return TokenType.WHITE_SPACE;
          }
        case 44: break;
        case 5: 
          { return TokenType.WHITE_SPACE;
          }
        case 45: break;
        case 8: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                   handleInState(stackFrame.getLastLexicalState());
          }
        case 46: break;
        case 26: 
          { if (isInterpolating()) {
                              return ElixirTypes.VALID_ESCAPE_SEQUENCE;
                            } else {
                              return fragmentType();
                            }
          }
        case 47: break;
        case 27: 
          { if (isInterpolating()) {
                             pushAndBegin(INTERPOLATION);
                             return ElixirTypes.INTERPOLATION_START;
                            } else {
                             return fragmentType();
                            }
          }
        case 48: break;
        case 10: 
          { return ElixirTypes.ATOM_FRAGMENT;
          }
        case 49: break;
        case 2: 
          { pushAndBegin(SIGIL);
                                              return ElixirTypes.TILDE;
          }
        case 50: break;
        case 16: 
          { yybegin(GROUP_HEREDOC_LINE_START);
          return fragmentType();
          }
        case 51: break;
        case 11: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                     yybegin(stackFrame.getLastLexicalState());
                     return ElixirTypes.ATOM_FRAGMENT;
          }
        case 52: break;
        case 14: 
          { return fragmentType();
          }
        case 53: break;
        case 4: 
          { return ElixirTypes.EOL;
          }
        case 54: break;
        case 29: 
          { handleInState(GROUP_HEREDOC_END);
          }
        case 55: break;
        case 22: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                     handleInState(stackFrame.getLastLexicalState());
          }
        case 56: break;
        case 7: 
          { startQuote(yytext());
                                              return promoterType();
          }
        case 57: break;
        case 13: 
          { /* At the end of the quote, return the state (YYINITIAL or INTERPOLATION) before ATOM_START as
                        anything after the closing quote should be handle by the state prior to ATOM_START.  Without
                        this, EOL and WHITESPACE won't be handled correctly */
                     org.elixir_lang.lexer.StackFrame stackFrame = pop();
                     yybegin(stackFrame.getLastLexicalState());
                     startQuote(yytext());
                     return promoterType();
          }
        case 58: break;
        case 21: 
          { nameSigil(yytext());
                               yybegin(NAMED_SIGIL);
                               return sigilNameType();
          }
        case 59: break;
        case 17: 
          { handleInState(GROUP_HEREDOC_LINE_BODY);
          }
        case 60: break;
        case 30: 
          { setPromoter(yytext());
                             yybegin(GROUP_HEREDOC_START);
                             return promoterType();
          }
        case 61: break;
        case 25: 
          { return ElixirTypes.NUMBER;
          }
        case 62: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
