/* The following code was generated by JFlex 1.4.3 on 11/29/14 8:11 PM */

package org.elixir_lang;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;
import org.elixir_lang.lexer.group.*;
import org.elixir_lang.psi.ElixirTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/29/14 8:11 PM from the specification file
 * <tt>/Users/luke.imhoff/git/KronicDeth/intellij-elixir/src/org/elixir_lang/Elixir.flex</tt>
 */
public class ElixirFlexLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int UNKNOWN_BASE_INTEGER = 32;
  public static final int HEXADECIMAL_INTEGER = 20;
  public static final int BINARY_INTEGER = 8;
  public static final int GROUP_HEREDOC_END = 12;
  public static final int INTERPOLATION = 22;
  public static final int KEYWORD_PAIR_MAYBE = 24;
  public static final int GROUP_HEREDOC_LINE_START = 16;
  public static final int SIGIL_MODIFIERS = 30;
  public static final int SIGIL = 28;
  public static final int GROUP_HEREDOC_START = 18;
  public static final int GROUP = 10;
  public static final int ATOM_START = 4;
  public static final int YYINITIAL = 0;
  public static final int GROUP_HEREDOC_LINE_BODY = 14;
  public static final int NAMED_SIGIL = 26;
  public static final int ATOM_BODY = 2;
  public static final int BASE_INTEGER_BASE = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 
    16, 16
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\47\1\44\1\0\1\50\1\45\22\0\1\47\1\14\1\71"+
    "\1\51\1\0\1\17\1\7\1\70\1\67\1\66\1\34\1\30\1\41"+
    "\1\25\1\24\1\35\1\52\1\56\6\60\2\37\1\31\1\43\1\1"+
    "\1\15\1\2\1\36\1\32\1\42\1\55\2\42\1\63\1\42\21\53"+
    "\1\57\2\53\1\65\1\26\1\64\1\16\1\40\1\0\1\10\1\54"+
    "\1\61\1\11\1\5\1\72\1\62\1\4\1\33\2\62\1\73\1\62"+
    "\1\6\1\22\2\62\1\27\1\74\1\23\1\75\1\62\1\3\1\46"+
    "\2\62\1\20\1\13\1\21\1\12\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\21\0\1\1\2\2\4\3\1\4\1\3\1\5\1\6"+
    "\1\7\1\10\1\7\1\11\1\1\2\3\1\12\1\13"+
    "\1\1\1\13\1\14\1\15\1\3\1\16\1\1\1\17"+
    "\1\20\1\21\1\22\1\23\1\1\1\24\1\25\1\17"+
    "\1\26\1\27\1\30\1\31\2\32\1\3\1\33\1\34"+
    "\1\35\1\33\2\36\3\37\1\36\1\37\1\1\5\36"+
    "\1\1\1\37\2\36\1\1\1\36\1\1\1\36\1\37"+
    "\1\1\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\46\1\50\1\51\1\52\3\51\1\0\1\53"+
    "\1\51\4\54\1\55\1\1\1\56\1\57\1\60\1\56"+
    "\1\61\3\62\2\63\1\64\1\65\1\66\1\65\1\67"+
    "\1\70\1\67\1\0\1\71\1\72\1\0\1\2\1\73"+
    "\5\3\1\74\1\3\1\0\1\72\1\75\1\76\1\77"+
    "\1\76\2\0\1\100\1\75\1\3\1\71\1\101\1\24"+
    "\1\0\1\102\1\103\1\104\2\105\2\0\1\21\2\106"+
    "\2\0\1\107\1\3\1\0\1\36\3\0\1\36\2\0"+
    "\2\36\2\0\1\36\3\110\1\111\4\0\1\112\2\0"+
    "\1\3\1\113\1\7\1\114\2\74\1\7\1\75\1\115"+
    "\1\116\1\3\1\117\2\105\2\17\1\120\1\3\1\0"+
    "\1\110\1\0\1\121\1\0\1\122\1\123\1\124\1\125"+
    "\1\126\1\105\2\0\1\3\1\0\1\127\2\0\1\17"+
    "\1\130\12\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\u0136\0\u0174\0\u01b2"+
    "\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364\0\u03a2"+
    "\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\u0516\0\u0554\0\u0592"+
    "\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8\0\u0706\0\u0744\0\u0782"+
    "\0\u07c0\0\u07fe\0\u083c\0\u087a\0\u08b8\0\u08f6\0\u0934\0\u0972"+
    "\0\u041e\0\u09b0\0\u041e\0\u09ee\0\u0a2c\0\u041e\0\u0a6a\0\u041e"+
    "\0\u041e\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u041e\0\u041e\0\u041e"+
    "\0\u041e\0\u0ba0\0\u0bde\0\u0c1c\0\u041e\0\u0c5a\0\u041e\0\u0c98"+
    "\0\u0cd6\0\u0d14\0\u0d52\0\u041e\0\u0d90\0\u0dce\0\u0e0c\0\u0e4a"+
    "\0\u0e88\0\u0ec6\0\u0f04\0\u0f42\0\u0f80\0\u0fbe\0\u0ffc\0\u103a"+
    "\0\u1078\0\u10b6\0\u10f4\0\u1132\0\u041e\0\u1170\0\u11ae\0\u041e"+
    "\0\u041e\0\u041e\0\u041e\0\u041e\0\u041e\0\u041e\0\u11ec\0\u122a"+
    "\0\u1268\0\u041e\0\u041e\0\u12a6\0\u12e4\0\u1322\0\u1360\0\u041e"+
    "\0\u139e\0\u041e\0\u13dc\0\u141a\0\u1458\0\u041e\0\u1496\0\u041e"+
    "\0\u14d4\0\u1512\0\u1550\0\u041e\0\u041e\0\u158e\0\u15cc\0\u041e"+
    "\0\u160a\0\u041e\0\u041e\0\u041e\0\u1648\0\u041e\0\u1686\0\u16c4"+
    "\0\u1702\0\u041e\0\u1740\0\u1740\0\u041e\0\u041e\0\u177e\0\u041e"+
    "\0\u17bc\0\u17fa\0\u1838\0\u1876\0\u18b4\0\u18f2\0\u041e\0\u1930"+
    "\0\u196e\0\u041e\0\u041e\0\u19ac\0\u19ea\0\u041e\0\u0516\0\u1a28"+
    "\0\u1a66\0\u041e\0\u041e\0\u1aa4\0\u1ae2\0\u041e\0\u0516\0\u041e"+
    "\0\u1b20\0\u1b5e\0\u1b9c\0\u041e\0\u041e\0\u1bda\0\u1c18\0\u1c56"+
    "\0\u0516\0\u1c94\0\u1cd2\0\u1d10\0\u1d10\0\u1d4e\0\u1d8c\0\u1dca"+
    "\0\u1e08\0\u1e46\0\u1e84\0\u1ec2\0\u1f00\0\u0fbe\0\u1f3e\0\u041e"+
    "\0\u1f7c\0\u1fba\0\u041e\0\u1ff8\0\u141a\0\u2036\0\u2074\0\u041e"+
    "\0\u20b2\0\u20f0\0\u212e\0\u0516\0\u0516\0\u0516\0\u041e\0\u0516"+
    "\0\u041e\0\u041e\0\u041e\0\u041e\0\u216c\0\u041e\0\u21aa\0\u21e8"+
    "\0\u2226\0\u1bda\0\u041e\0\u2264\0\u1170\0\u22a2\0\u22e0\0\u041e"+
    "\0\u231e\0\u041e\0\u041e\0\u041e\0\u0516\0\u0516\0\u235c\0\u239a"+
    "\0\u23d8\0\u2416\0\u2454\0\u041e\0\u2492\0\u24d0\0\u250e\0\u0516"+
    "\0\u254c\0\u258a\0\u25c8\0\u2606\0\u2644\0\u2682\0\u26c0\0\u26fe"+
    "\0\u273c\0\u277a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\26\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\22\1\42\1\43\1\44\1\45\1\46\1\26"+
    "\1\47\1\50\1\51\1\52\2\53\1\54\1\55\1\26"+
    "\1\56\1\57\1\60\1\61\1\62\1\26\2\63\1\64"+
    "\1\65\1\57\1\26\1\57\1\55\1\57\1\55\2\26"+
    "\1\57\1\66\1\67\1\70\1\71\1\72\1\73\1\74"+
    "\3\26\3\75\4\76\1\75\2\76\2\75\1\77\5\75"+
    "\2\76\3\75\1\76\2\75\2\76\2\75\1\77\2\76"+
    "\1\75\1\76\2\75\1\100\1\76\3\75\12\76\6\75"+
    "\4\76\1\22\1\101\1\102\1\103\2\104\1\105\1\106"+
    "\1\107\1\104\1\110\1\111\1\112\1\113\1\114\1\115"+
    "\1\116\1\22\1\117\1\104\1\120\1\121\1\122\1\104"+
    "\1\123\1\124\1\125\1\126\2\125\2\22\1\104\1\22"+
    "\1\104\2\22\1\127\1\104\4\22\3\104\1\22\1\104"+
    "\1\22\3\104\4\22\2\130\4\104\3\0\4\131\1\0"+
    "\2\131\10\0\2\131\3\0\1\131\3\0\1\131\6\0"+
    "\1\131\3\0\1\132\4\0\1\131\1\133\1\134\1\0"+
    "\1\135\1\0\3\131\6\0\4\131\3\136\4\137\1\136"+
    "\2\137\10\136\2\137\3\136\1\137\3\136\1\137\3\136"+
    "\1\137\2\136\1\137\2\136\1\140\1\137\3\136\1\141"+
    "\3\137\1\141\5\137\6\136\4\137\2\142\1\143\10\142"+
    "\1\143\5\142\1\143\4\142\1\144\6\142\1\143\7\142"+
    "\1\145\3\142\1\146\12\142\1\143\1\142\1\143\1\142"+
    "\2\143\4\142\70\0\2\147\4\0\26\142\1\144\15\142"+
    "\1\150\1\151\3\142\1\146\24\142\45\152\1\153\1\152"+
    "\2\154\17\152\2\155\4\152\44\22\1\156\1\157\30\22"+
    "\3\160\2\161\1\162\1\161\1\160\2\162\10\160\2\161"+
    "\3\160\1\161\3\160\1\161\3\160\1\162\2\160\1\162"+
    "\2\160\1\163\1\161\3\160\1\162\1\161\3\162\1\161"+
    "\2\162\1\161\1\162\6\160\1\162\3\161\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\26"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\164"+
    "\1\42\1\43\1\44\1\45\1\46\1\26\1\47\1\50"+
    "\1\51\1\52\2\53\1\54\1\55\1\26\1\56\1\57"+
    "\1\60\1\61\1\62\1\26\2\63\1\64\1\65\1\57"+
    "\1\26\1\57\1\55\1\57\1\55\2\26\1\57\1\66"+
    "\1\67\1\70\1\71\1\72\1\73\1\74\3\26\31\165"+
    "\1\166\13\165\1\167\30\165\1\22\1\170\11\22\1\170"+
    "\4\22\1\170\14\22\1\170\6\22\1\0\20\22\1\170"+
    "\1\22\1\170\2\171\7\22\4\172\1\22\2\172\10\22"+
    "\2\172\3\22\1\172\3\22\1\172\6\22\1\172\2\22"+
    "\1\127\1\172\4\22\3\172\1\22\1\172\1\22\3\172"+
    "\6\22\4\172\3\173\4\174\1\173\2\174\10\173\2\174"+
    "\3\173\1\174\3\173\1\174\11\173\1\175\1\174\5\173"+
    "\1\174\4\173\2\174\7\173\4\174\3\176\4\177\1\176"+
    "\2\177\10\176\2\177\3\176\1\177\3\176\1\177\3\176"+
    "\1\177\2\176\1\177\2\176\1\200\1\177\3\176\12\177"+
    "\6\176\4\177\77\0\1\201\1\202\7\0\1\203\1\204"+
    "\1\0\1\205\7\0\1\206\52\0\1\204\12\0\1\205"+
    "\63\0\1\26\1\207\2\26\1\0\2\26\2\0\1\210"+
    "\5\0\2\26\3\0\1\26\3\0\1\26\2\0\1\210"+
    "\2\26\1\0\1\26\3\0\1\26\3\0\12\26\6\0"+
    "\4\26\3\0\4\26\1\0\2\26\2\0\1\210\5\0"+
    "\2\26\3\0\1\26\3\0\1\26\2\0\1\210\2\26"+
    "\1\0\1\26\3\0\1\26\3\0\12\26\6\0\4\26"+
    "\3\0\3\26\1\211\1\0\2\26\2\0\1\210\5\0"+
    "\2\26\3\0\1\26\3\0\1\26\2\0\1\210\2\26"+
    "\1\0\1\26\3\0\1\26\3\0\12\26\6\0\4\26"+
    "\3\0\4\26\1\0\2\26\2\0\1\210\5\0\1\212"+
    "\1\26\3\0\1\26\3\0\1\213\2\0\1\210\2\26"+
    "\1\0\1\26\3\0\1\26\3\0\12\26\6\0\4\26"+
    "\7\0\1\214\71\0\3\26\1\215\1\0\2\26\2\0"+
    "\1\210\5\0\2\26\3\0\1\26\3\0\1\26\2\0"+
    "\1\210\2\26\1\0\1\26\3\0\1\26\3\0\12\26"+
    "\6\0\4\26\2\0\1\203\7\0\1\216\65\0\1\217"+
    "\10\0\1\220\77\0\1\221\62\0\1\222\7\0\1\223"+
    "\2\0\1\221\76\0\1\224\77\0\1\225\76\0\1\226"+
    "\57\0\4\26\1\0\2\26\2\0\1\210\5\0\2\26"+
    "\3\0\1\227\3\0\1\26\2\0\1\210\2\26\1\0"+
    "\1\26\3\0\1\26\3\0\12\26\6\0\4\26\3\0"+
    "\4\26\1\0\2\26\2\0\1\210\5\0\2\26\3\0"+
    "\1\230\3\0\1\26\2\0\1\210\2\26\1\0\1\26"+
    "\3\0\1\26\3\0\12\26\6\0\4\26\24\0\1\231"+
    "\53\0\1\232\22\0\1\202\76\0\1\206\15\0\1\233"+
    "\1\234\60\0\1\202\76\0\1\235\12\0\2\236\1\0"+
    "\1\236\31\0\3\26\1\237\1\0\2\26\2\0\1\210"+
    "\5\0\2\26\3\0\1\26\3\0\1\26\2\0\1\210"+
    "\2\26\1\0\1\26\3\0\1\26\3\0\12\26\6\0"+
    "\4\26\26\240\1\241\15\240\1\0\31\240\24\0\1\242"+
    "\12\0\1\55\1\243\11\0\1\55\3\0\1\55\1\0"+
    "\1\55\20\0\4\57\1\0\2\57\2\0\1\244\5\0"+
    "\2\57\3\0\1\57\3\0\1\57\2\0\1\244\2\57"+
    "\1\0\1\57\3\0\1\57\3\0\12\57\6\0\4\57"+
    "\44\0\1\61\100\0\2\63\25\0\44\64\2\0\30\64"+
    "\3\0\4\245\1\0\2\245\10\0\1\246\1\245\1\242"+
    "\2\0\1\245\3\0\1\245\3\0\1\55\1\243\1\0"+
    "\1\245\3\0\1\245\3\0\1\55\3\245\1\55\1\245"+
    "\1\55\3\245\6\0\4\245\70\0\1\247\76\0\1\250"+
    "\7\0\3\26\1\251\1\0\1\252\1\26\2\0\1\210"+
    "\5\0\2\26\3\0\1\26\3\0\1\26\2\0\1\210"+
    "\2\26\1\0\1\26\3\0\1\26\3\0\12\26\6\0"+
    "\4\26\3\0\4\76\1\0\2\76\10\0\2\76\3\0"+
    "\1\76\2\0\2\76\3\0\2\76\1\0\1\76\3\0"+
    "\1\76\3\0\12\76\6\0\4\76\44\0\1\75\32\0"+
    "\1\253\1\125\7\0\1\254\1\255\1\0\1\125\7\0"+
    "\1\125\52\0\1\255\12\0\1\125\64\0\1\256\113\0"+
    "\1\257\62\0\1\260\74\0\1\261\71\0\1\254\7\0"+
    "\1\262\65\0\1\125\10\0\1\263\77\0\1\264\62\0"+
    "\1\125\7\0\1\125\2\0\1\264\76\0\1\265\77\0"+
    "\1\266\76\0\1\125\103\0\1\125\72\0\1\267\53\0"+
    "\1\125\22\0\1\125\76\0\1\125\77\0\1\125\76\0"+
    "\1\125\52\0\1\125\133\0\1\22\34\0\4\137\1\0"+
    "\2\137\10\0\2\137\3\0\1\137\3\0\1\137\3\0"+
    "\1\137\2\0\1\137\3\0\1\137\4\0\3\137\1\0"+
    "\5\137\6\0\4\137\44\0\1\136\103\0\1\141\3\0"+
    "\1\141\17\0\45\270\1\271\1\272\27\270\44\0\1\142"+
    "\51\0\1\273\145\0\2\274\50\0\1\150\75\0\1\152"+
    "\100\0\2\275\17\0\2\276\74\0\2\277\50\0\1\156"+
    "\34\0\2\161\1\0\1\161\13\0\2\161\3\0\1\161"+
    "\3\0\1\161\12\0\1\161\4\0\1\161\3\0\1\161"+
    "\2\0\1\161\10\0\3\161\5\0\1\162\2\0\2\162"+
    "\25\0\1\162\2\0\1\162\7\0\1\162\1\0\3\162"+
    "\1\0\2\162\1\0\1\162\6\0\1\162\47\0\1\160"+
    "\75\0\2\300\1\0\1\300\72\0\1\165\121\0\2\301"+
    "\50\0\1\173\34\0\4\177\1\0\2\177\10\0\2\177"+
    "\3\0\1\177\3\0\1\177\3\0\1\177\2\0\1\177"+
    "\3\0\1\177\3\0\12\177\6\0\4\177\44\0\1\176"+
    "\32\0\1\217\1\302\7\0\1\217\65\0\1\217\76\0"+
    "\2\26\1\303\1\26\1\0\2\26\2\0\1\210\5\0"+
    "\2\26\3\0\1\26\3\0\1\26\2\0\1\210\2\26"+
    "\1\0\1\26\3\0\1\26\3\0\12\26\6\0\4\26"+
    "\3\0\4\26\1\0\1\26\1\304\2\0\1\210\5\0"+
    "\2\26\3\0\1\26\3\0\1\26\2\0\1\210\2\26"+
    "\1\0\1\26\3\0\1\26\3\0\12\26\6\0\4\26"+
    "\3\0\4\26\1\0\2\26\2\0\1\210\5\0\1\26"+
    "\1\305\3\0\1\26\3\0\1\26\2\0\1\210\2\26"+
    "\1\0\1\26\3\0\1\26\3\0\12\26\6\0\4\26"+
    "\3\0\4\26\1\0\2\26\2\0\1\210\5\0\2\26"+
    "\3\0\1\26\3\0\1\26\2\0\1\210\2\26\1\0"+
    "\1\26\3\0\1\26\3\0\12\26\6\0\1\26\1\306"+
    "\2\26\7\0\1\307\71\0\4\26\1\0\1\26\1\310"+
    "\2\0\1\210\5\0\2\26\3\0\1\26\3\0\1\26"+
    "\2\0\1\210\2\26\1\0\1\26\3\0\1\26\3\0"+
    "\12\26\6\0\4\26\12\0\1\311\76\0\1\312\77\0"+
    "\1\223\76\0\1\313\100\0\1\314\57\0\4\26\1\0"+
    "\2\26\2\0\1\210\5\0\2\26\3\0\1\26\3\0"+
    "\1\26\2\0\1\210\2\26\1\0\1\26\3\0\1\26"+
    "\3\0\12\26\6\0\3\26\1\315\24\0\1\210\115\0"+
    "\1\233\62\0\1\316\44\0\45\240\1\317\1\320\27\240"+
    "\37\0\1\321\12\0\1\321\3\0\1\321\1\0\1\321"+
    "\54\0\1\55\12\0\1\55\3\0\1\55\1\0\1\55"+
    "\67\0\1\322\3\0\1\322\1\0\1\322\105\0\1\323"+
    "\76\0\1\323\7\0\4\26\1\0\2\26\2\0\1\210"+
    "\5\0\2\26\3\0\1\26\3\0\1\26\2\0\1\210"+
    "\2\26\1\0\1\26\3\0\1\26\3\0\12\26\6\0"+
    "\1\26\1\324\2\26\1\0\1\125\1\255\7\0\1\125"+
    "\65\0\1\125\100\0\1\325\113\0\1\125\61\0\1\125"+
    "\77\0\1\125\76\0\1\125\76\0\1\125\77\0\1\125"+
    "\76\0\1\125\103\0\1\125\115\0\1\270\36\0\1\326"+
    "\2\0\2\326\6\0\1\327\16\0\1\326\2\0\1\326"+
    "\7\0\1\326\1\0\3\326\1\0\2\326\1\0\1\326"+
    "\6\0\1\326\73\0\2\330\74\0\2\331\74\0\2\332"+
    "\74\0\2\333\6\0\1\334\76\0\3\26\1\335\1\0"+
    "\2\26\2\0\1\210\5\0\2\26\3\0\1\26\3\0"+
    "\1\26\2\0\1\210\2\26\1\0\1\26\3\0\1\26"+
    "\3\0\12\26\6\0\4\26\3\0\2\26\1\336\1\26"+
    "\1\0\2\26\2\0\1\210\5\0\2\26\3\0\1\26"+
    "\3\0\1\26\2\0\1\210\2\26\1\0\1\26\3\0"+
    "\1\26\3\0\12\26\6\0\4\26\44\0\1\240\36\0"+
    "\1\337\2\0\2\337\6\0\1\340\16\0\1\337\2\0"+
    "\1\337\7\0\1\337\1\0\3\337\1\0\2\337\1\0"+
    "\1\337\6\0\1\337\10\0\1\341\31\0\1\321\1\242"+
    "\11\0\1\321\3\0\1\321\1\0\1\321\2\0\1\341"+
    "\15\0\4\26\1\0\2\26\2\0\1\210\5\0\2\26"+
    "\3\0\1\26\3\0\1\26\2\0\1\210\2\26\1\0"+
    "\1\26\3\0\1\26\3\0\12\26\6\0\2\26\1\342"+
    "\1\26\5\0\1\270\2\0\2\270\25\0\1\270\2\0"+
    "\1\270\7\0\1\270\1\0\3\270\1\0\2\270\1\0"+
    "\1\270\6\0\1\270\10\0\1\343\2\0\2\343\25\0"+
    "\1\343\2\0\1\343\7\0\1\343\1\0\3\343\1\0"+
    "\2\343\1\0\1\343\6\0\1\343\73\0\2\344\11\0"+
    "\1\240\2\0\2\240\25\0\1\240\2\0\1\240\7\0"+
    "\1\240\1\0\3\240\1\0\2\240\1\0\1\240\6\0"+
    "\1\240\10\0\1\345\2\0\2\345\25\0\1\345\2\0"+
    "\1\345\7\0\1\345\1\0\3\345\1\0\2\345\1\0"+
    "\1\345\6\0\1\345\30\0\1\346\2\0\1\346\6\0"+
    "\1\347\12\0\1\347\3\0\1\347\1\0\1\347\20\0"+
    "\2\26\1\350\1\26\1\0\2\26\2\0\1\210\5\0"+
    "\2\26\3\0\1\26\3\0\1\26\2\0\1\210\2\26"+
    "\1\0\1\26\3\0\1\26\3\0\12\26\6\0\4\26"+
    "\5\0\1\351\2\0\2\351\7\0\1\270\15\0\1\351"+
    "\2\0\1\351\7\0\1\351\1\0\3\351\1\0\2\351"+
    "\1\0\1\351\6\0\1\351\10\0\1\352\2\0\2\352"+
    "\7\0\1\240\15\0\1\352\2\0\1\352\7\0\1\352"+
    "\1\0\3\352\1\0\2\352\1\0\1\352\6\0\1\352"+
    "\42\0\1\347\12\0\1\347\3\0\1\347\1\0\1\347"+
    "\54\0\1\347\1\346\11\0\1\347\3\0\1\347\1\0"+
    "\1\347\22\0\1\353\2\0\2\353\7\0\1\270\15\0"+
    "\1\353\2\0\1\353\7\0\1\353\1\0\3\353\1\0"+
    "\2\353\1\0\1\353\6\0\1\353\10\0\1\354\2\0"+
    "\2\354\7\0\1\240\15\0\1\354\2\0\1\354\7\0"+
    "\1\354\1\0\3\354\1\0\2\354\1\0\1\354\6\0"+
    "\1\354\10\0\1\355\2\0\2\355\7\0\1\270\15\0"+
    "\1\355\2\0\1\355\7\0\1\355\1\0\3\355\1\0"+
    "\2\355\1\0\1\355\6\0\1\355\10\0\1\356\2\0"+
    "\2\356\7\0\1\240\15\0\1\356\2\0\1\356\7\0"+
    "\1\356\1\0\3\356\1\0\2\356\1\0\1\356\6\0"+
    "\1\356\10\0\1\357\2\0\2\357\7\0\1\270\15\0"+
    "\1\357\2\0\1\357\7\0\1\357\1\0\3\357\1\0"+
    "\2\357\1\0\1\357\6\0\1\357\10\0\1\360\2\0"+
    "\2\360\7\0\1\240\15\0\1\360\2\0\1\360\7\0"+
    "\1\360\1\0\3\360\1\0\2\360\1\0\1\360\6\0"+
    "\1\360\10\0\1\361\2\0\2\361\7\0\1\270\15\0"+
    "\1\361\2\0\1\361\7\0\1\361\1\0\3\361\1\0"+
    "\2\361\1\0\1\361\6\0\1\361\10\0\1\362\2\0"+
    "\2\362\7\0\1\240\15\0\1\362\2\0\1\362\7\0"+
    "\1\362\1\0\3\362\1\0\2\362\1\0\1\362\6\0"+
    "\1\362\24\0\1\270\75\0\1\240\54\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10168];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\21\0\1\11\26\1\1\11\1\1\1\11\2\1\1\11"+
    "\1\1\2\11\4\1\4\11\3\1\1\11\1\1\1\11"+
    "\4\1\1\11\20\1\1\11\2\1\7\11\3\1\2\11"+
    "\3\1\1\0\1\11\1\1\1\11\3\1\1\11\1\1"+
    "\1\11\3\1\2\11\2\1\1\11\1\1\3\11\1\1"+
    "\1\11\2\1\1\0\1\11\1\1\1\0\2\11\1\1"+
    "\1\11\5\1\1\0\1\11\2\1\2\11\2\0\1\11"+
    "\3\1\2\11\1\0\1\1\1\11\1\1\1\11\1\1"+
    "\2\0\2\11\1\1\2\0\2\1\1\0\1\1\3\0"+
    "\1\1\2\0\2\1\2\0\1\1\1\11\2\1\1\11"+
    "\4\0\1\11\2\0\4\1\1\11\1\1\4\11\1\1"+
    "\1\11\4\1\1\11\1\1\1\0\1\1\1\0\1\11"+
    "\1\0\3\11\3\1\2\0\1\1\1\0\1\11\2\0"+
    "\2\1\12\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private org.elixir_lang.lexer.Stack stack = new org.elixir_lang.lexer.Stack();

  private void startQuote(CharSequence quotePromoterCharSequence) {
    String quotePromoter = quotePromoterCharSequence.toString();
    stack.push(quotePromoter, yystate());

    if (Base.isHeredocPromoter(quotePromoter)) {
      yybegin(GROUP_HEREDOC_START);
    } else {
      yybegin(GROUP);
    }
  }

  private IElementType fragmentType() {
    return stack.fragmentType();
  }

  private void handleInState(int nextLexicalState) {
    yypushback(yylength());
    yybegin(nextLexicalState);
  }

  private boolean isTerminator(CharSequence terminator) {
    return stack.terminator().equals(terminator.toString());
  }

  private boolean isInterpolating() {
    return stack.isInterpolating();
  }

  private boolean isInterpolatingSigil(CharSequence sigilName) {
    if (sigilName.length() != 1) {
      throw new IllegalArgumentException("sigil names can only be 1 character long");
    }

    return isInterpolatingSigil(sigilName.charAt(0));
  }

  private boolean isInterpolatingSigil(char sigilName) {
    return (sigilName >= 'a' && sigilName <= 'z');
  }

  private boolean isSigil() {
    return stack.isSigil();
  }

  private void nameSigil(CharSequence sigilName) {
    stack.nameSigil(sigilName.charAt(0));
  }

  private org.elixir_lang.lexer.StackFrame pop() {
    return stack.pop();
  }

  private org.elixir_lang.lexer.group.Quote promotedQuote(CharSequence promoterCharSequence) {
    // CharSequences don't look up correctly, so convert to String, which do.
    String promoter = promoterCharSequence.toString();
    org.elixir_lang.lexer.group.Quote quote = org.elixir_lang.lexer.group.Quote.fetch(promoter);

    return quote;
  }

  private IElementType promoterType() {
    return stack.promoterType();
  }

  private void setPromoter(CharSequence promoter) {
    stack.setPromoter(promoter.toString());
  }

  private IElementType sigilNameType() {
    return stack.sigilNameType();
  }

  // public for testing
  public void pushAndBegin(int lexicalState) {
    stack.push(yystate());
    yybegin(lexicalState);
  }

  private IElementType terminatorType() {
    return stack.terminatorType();
  }


  public ElixirFlexLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ElixirFlexLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 15: 
          { return ElixirTypes.NUMBER;
          }
        case 89: break;
        case 38: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                            handleInState(stackFrame.getLastLexicalState());
          }
        case 90: break;
        case 68: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.IN_OPERATOR;
          }
        case 91: break;
        case 69: 
          { return ElixirTypes.CHAR_TOKEN;
          }
        case 92: break;
        case 8: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.MATCH_OPERATOR;
          }
        case 93: break;
        case 61: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.OR_OPERATOR;
          }
        case 94: break;
        case 80: 
          { startQuote(yytext());
                                               return promoterType();
          }
        case 95: break;
        case 55: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                                  handleInState(stackFrame.getLastLexicalState());
          }
        case 96: break;
        case 31: 
          { yybegin(ATOM_BODY);
                     return ElixirTypes.ATOM_FRAGMENT;
          }
        case 97: break;
        case 30: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                     yybegin(stackFrame.getLastLexicalState());
                     return ElixirTypes.ATOM_FRAGMENT;
          }
        case 98: break;
        case 66: 
          { return ElixirTypes.TYPE_OPERATOR;
          }
        case 99: break;
        case 81: 
          { if (isTerminator(yytext())) {
                                      if (isSigil()) {
                                        yybegin(SIGIL_MODIFIERS);
                                        return terminatorType();
                                      } else {
                                        org.elixir_lang.lexer.StackFrame stackFrame = pop();
                                        yybegin(stackFrame.getLastLexicalState());
                                        return stackFrame.terminatorType();
                                      }
                                   } else {
                                      handleInState(GROUP_HEREDOC_LINE_BODY);
                                   }
          }
        case 100: break;
        case 29: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                   yybegin(stackFrame.getLastLexicalState());
                   return ElixirTypes.ATOM_FRAGMENT;
          }
        case 101: break;
        case 88: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.FALSE;
          }
        case 102: break;
        case 5: 
          { pushAndBegin(SIGIL);
                                               return ElixirTypes.TILDE;
          }
        case 103: break;
        case 82: 
          { handleInState(GROUP_HEREDOC_END);
          }
        case 104: break;
        case 33: 
          { yybegin(UNKNOWN_BASE_INTEGER);
                                   return ElixirTypes.UNKNOWN_INTEGER_BASE;
          }
        case 105: break;
        case 70: 
          // lookahead expression with fixed base length
          zzMarkedPos = zzStartRead + 1;
          { pushAndBegin(BASE_INTEGER_BASE);
                                                return ElixirTypes.BASE_INTEGER_PREFIX;
          }
        case 106: break;
        case 28: 
          { return ElixirTypes.ATOM_FRAGMENT;
          }
        case 107: break;
        case 73: 
          { if (isInterpolating()) {
                             pushAndBegin(INTERPOLATION);
                             return ElixirTypes.INTERPOLATION_START;
                            } else {
                             return fragmentType();
                            }
          }
        case 108: break;
        case 46: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                                 handleInState(stackFrame.getLastLexicalState());
          }
        case 109: break;
        case 42: 
          { if (isTerminator(yytext())) {
                         if (isSigil()) {
                           yybegin(SIGIL_MODIFIERS);
                           return terminatorType();
                         } else {
                           org.elixir_lang.lexer.StackFrame stackFrame = pop();
                           yybegin(stackFrame.getLastLexicalState());
                           return stackFrame.terminatorType();
                         }
                       } else {
                         return fragmentType();
                       }
          }
        case 110: break;
        case 72: 
          { if (isInterpolating()) {
                              return ElixirTypes.VALID_ESCAPE_SEQUENCE;
                            } else {
                              return fragmentType();
                            }
          }
        case 111: break;
        case 86: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.TRUE;
          }
        case 112: break;
        case 83: 
          { setPromoter(yytext());
                             yybegin(GROUP_HEREDOC_START);
                             return promoterType();
          }
        case 113: break;
        case 20: 
          { return TokenType.WHITE_SPACE;
          }
        case 114: break;
        case 60: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.AND_OPERATOR;
          }
        case 115: break;
        case 39: 
          { return ElixirTypes.INVALID_BINARY_DIGITS;
          }
        case 116: break;
        case 36: 
          { yybegin(BINARY_INTEGER);
                                   return ElixirTypes.OBSOLETE_BINARY_INTEGER_BASE;
          }
        case 117: break;
        case 19: 
          { return ElixirTypes.EOL;
          }
        case 118: break;
        case 32: 
          { /* At the end of the quote, return the state (YYINITIAL or INTERPOLATION) before ATOM_START as
                        anything after the closing quote should be handle by the state prior to ATOM_START.  Without
                        this, EOL and WHITESPACE won't be handled correctly */
                     org.elixir_lang.lexer.StackFrame stackFrame = pop();
                     yybegin(stackFrame.getLastLexicalState());
                     startQuote(yytext());
                     return promoterType();
          }
        case 119: break;
        case 23: 
          { return ElixirTypes.OPENING_BRACKET;
          }
        case 120: break;
        case 7: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.UNARY_OPERATOR;
          }
        case 121: break;
        case 77: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.HAT_OPERATOR;
          }
        case 122: break;
        case 84: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.BIT_STRING_OPERATOR;
          }
        case 123: break;
        case 49: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                                yybegin(stackFrame.getLastLexicalState());
                                return ElixirTypes.INTERPOLATION_END;
          }
        case 124: break;
        case 67: 
          // lookahead expression with fixed base length
          zzMarkedPos = zzStartRead + 1;
          { return ElixirTypes.COLON;
          }
        case 125: break;
        case 59: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.IN_MATCH_OPERATOR;
          }
        case 126: break;
        case 45: 
          { yybegin(GROUP_HEREDOC_LINE_START);
          return ElixirTypes.EOL;
          }
        case 127: break;
        case 13: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.AT_OPERATOR;
          }
        case 128: break;
        case 71: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.FN;
          }
        case 129: break;
        case 2: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.RELATIONAL_OPERATOR;
          }
        case 130: break;
        case 51: 
          { setPromoter(yytext());
                             yybegin(GROUP);
                             return promoterType();
          }
        case 131: break;
        case 50: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                              handleInState(stackFrame.getLastLexicalState());
          }
        case 132: break;
        case 64: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.TUPLE_OPERATOR;
          }
        case 133: break;
        case 17: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.ALIAS;
          }
        case 134: break;
        case 37: 
          { yybegin(HEXADECIMAL_INTEGER);
                                        return ElixirTypes.OBSOLETE_HEXADECIMAL_INTEGER_BASE;
          }
        case 135: break;
        case 56: 
          { return ElixirTypes.INVALID_UNKNOWN_BASE_DIGITS;
          }
        case 136: break;
        case 48: 
          { return ElixirTypes.VALID_HEXADECIMAL_DIGITS;
          }
        case 137: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 138: break;
        case 54: 
          { return ElixirTypes.SIGIL_MODIFIER;
          }
        case 139: break;
        case 6: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.PIPE_OPERATOR;
          }
        case 140: break;
        case 16: 
          { return ElixirTypes.COMMA;
          }
        case 141: break;
        case 22: 
          { return ElixirTypes.CLOSING_BRACKET;
          }
        case 142: break;
        case 9: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.STRUCT_OPERATOR;
          }
        case 143: break;
        case 57: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.TWO_OPERATOR;
          }
        case 144: break;
        case 18: 
          { return ElixirTypes.SEMICOLON;
          }
        case 145: break;
        case 47: 
          { return ElixirTypes.INVALID_HEXADECIMAL_DIGITS;
          }
        case 146: break;
        case 14: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.MULTIPLICATION_OPERATOR;
          }
        case 147: break;
        case 27: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                   handleInState(stackFrame.getLastLexicalState());
          }
        case 148: break;
        case 41: 
          { return fragmentType();
          }
        case 149: break;
        case 34: 
          { yybegin(HEXADECIMAL_INTEGER);
                                   return ElixirTypes.HEXADECIMAL_INTEGER_BASE;
          }
        case 150: break;
        case 53: 
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                     handleInState(stackFrame.getLastLexicalState());
          }
        case 151: break;
        case 75: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.END;
          }
        case 152: break;
        case 63: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.ASSOCIATION_OPERATOR;
          }
        case 153: break;
        case 10: 
          { return ElixirTypes.DOT_OPERATOR;
          }
        case 154: break;
        case 44: 
          { handleInState(GROUP_HEREDOC_LINE_BODY);
          }
        case 155: break;
        case 65: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.STAB_OPERATOR;
          }
        case 156: break;
        case 85: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.WHEN_OPERATOR;
          }
        case 157: break;
        case 11: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.DUAL_OPERATOR;
          }
        case 158: break;
        case 43: 
          { yybegin(GROUP_HEREDOC_LINE_START);
          return fragmentType();
          }
        case 159: break;
        case 76: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.NIL;
          }
        case 160: break;
        case 62: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.COMPARISON_OPERATOR;
          }
        case 161: break;
        case 87: 
          // lookahead expression with fixed lookahead length
          yypushback(3);
          { yybegin(GROUP_HEREDOC_END);
                                                  return TokenType.WHITE_SPACE;
          }
        case 162: break;
        case 78: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.MAP_OPERATOR;
          }
        case 163: break;
        case 74: 
          // lookahead expression with fixed base length
          zzMarkedPos = zzStartRead + 1;
          { org.elixir_lang.lexer.StackFrame stackFrame = pop();
                              yybegin(stackFrame.getLastLexicalState());
                              return ElixirTypes.KEYWORD_PAIR_COLON;
          }
        case 164: break;
        case 40: 
          { return ElixirTypes.VALID_BINARY_DIGITS;
          }
        case 165: break;
        case 26: 
          { /* return to KEYWORD_PAIR_MAYBE so that COLON after quote can be parsed
                                                  as KEYWORD_PAIR_COLON to differentiate between valid `<quote><colon>`
                                                  and invalid `<quote><space><colon>`. */
                                               pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               startQuote(yytext());
                                               return promoterType();
          }
        case 166: break;
        case 58: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.ARROW_OPERATOR;
          }
        case 167: break;
        case 52: 
          { nameSigil(yytext());
                               yybegin(NAMED_SIGIL);
                               return sigilNameType();
          }
        case 168: break;
        case 35: 
          { yybegin(BINARY_INTEGER);
                                   return ElixirTypes.BINARY_INTEGER_BASE;
          }
        case 169: break;
        case 3: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.IDENTIFIER;
          }
        case 170: break;
        case 24: 
          { return ElixirTypes.CLOSING_PARENTHESIS;
          }
        case 171: break;
        case 79: 
          // lookahead expression with fixed base length
          zzMarkedPos = zzStartRead + 1;
          { pushAndBegin(ATOM_START);
                                               return ElixirTypes.COLON;
          }
        case 172: break;
        case 21: 
          { return ElixirTypes.COMMENT;
          }
        case 173: break;
        case 12: 
          { pushAndBegin(ATOM_START);
                                               return ElixirTypes.COLON;
          }
        case 174: break;
        case 4: 
          { pushAndBegin(KEYWORD_PAIR_MAYBE);
                                               return ElixirTypes.CAPTURE_OPERATOR;
          }
        case 175: break;
        case 25: 
          { return ElixirTypes.OPENING_PARENTHESIS;
          }
        case 176: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
