package org.elixir_lang

import com.intellij.psi.PsiPolyVariantReference
import com.intellij.psi.ResolveResult
import com.intellij.psi.ResolveState
import com.intellij.psi.util.isAncestor
import org.elixir_lang.errorreport.Logger
import org.elixir_lang.psi.CallDefinitionClause
import org.elixir_lang.psi.CallDefinitionClause.enclosingModularMacroCall
import org.elixir_lang.psi.call.Call
import org.elixir_lang.psi.call.qualification.Qualified
import org.elixir_lang.psi.impl.ElixirPsiImplUtil

fun safeMultiResolve(reference: PsiPolyVariantReference, incompleteCode: Boolean): Array<ResolveResult> =
    try {
        reference.multiResolve(incompleteCode)
    } catch (stackOverflowError: StackOverflowError) {
        Logger.error(PsiPolyVariantReference::class.java, "StackOverflow resolving reference", reference.element)

        emptyArray()
    }

/**
 * Calls currently having their macro-ness decided by [resolvesToMacro], per thread.
 *
 * Resolving a call to decide whether its arguments are variable declarations re-enters variable
 * resolution, which can ask the same question about the same call. [resolvesToModularName] has the
 * same hazard and guards it with the `ENTRANCE` of a `ResolveState`; the callers here hold no
 * `ResolveState`, so the guard is kept beside the function instead of widening their signatures.
 */
private val RESOLVING_MACRO: ThreadLocal<MutableSet<Call>> = ThreadLocal.withInitial { mutableSetOf<Call>() }

/**
 * Whether [call] resolves to a `defmacro` rather than a `def`.
 *
 * A macro's arguments are quoted, so in a match they can bind, while a function's arguments are
 * values and bind nothing. The two are indistinguishable syntactically, so
 * [org.elixir_lang.reference.Callable.isVariable] has to resolve the call to tell them apart.
 *
 * Answers `false` rather than guessing when the call does not resolve - a macro from a `.beam`
 * dependency, or one generated by `Record.defrecord` or injected by `use`, may not resolve at all.
 * That keeps the unresolved case behaving exactly as it did before
 * [#305](https://github.com/KronicDeth/intellij-elixir/issues/305): not a declaration.
 */
fun resolvesToMacro(call: Call): Boolean {
    val inProgress = RESOLVING_MACRO.get()

    // already deciding this same call further up the stack, so don't recurse into it again
    if (!inProgress.add(call)) return false

    return try {
        (call.reference as? PsiPolyVariantReference)
            ?.let { safeMultiResolve(it, false) }
            ?.any { resolveResult ->
                resolveResult.isValidResult &&
                        (resolveResult.element as? Call)?.let { resolved ->
                            CallDefinitionClause.isMacro(resolved) &&
                                    // don't treat the signature as a call of the macro
                                    !resolved.isAncestor(call)
                        } == true
            }
            ?: false
    } finally {
        inProgress.remove(call)
    }
}

fun resolvesToModularName(call: Call, state: ResolveState, modularName: String): Boolean =
        // it is not safe to call `multiResolve` on the call's reference if that `call` is currently being resolved.
        if (!isBeingResolved(call, state)) {
            call.reference?.let { it as PsiPolyVariantReference }?.let { reference ->
                safeMultiResolve(reference, false).any { resolveResult ->
                    if (resolveResult.isValidResult) {
                        resolveResult.element?.let { it as? Call }?.let { resolved ->
                            CallDefinitionClause.isMacro(resolved) &&
                                    // don't treat the signature as a call of the function
                                    !resolved.isAncestor(call) &&
                                    enclosingModularMacroCall(resolved)?.name == modularName
                        } ?: false
                    } else {
                        false
                    }
                }
            } ?: false
        } else {
            false
        }

private fun isBeingResolved(call: Call, state: ResolveState): Boolean =
        call.isEquivalentTo(state.get(ElixirPsiImplUtil.ENTRANCE)) || qualifierIsBeingResolved(call, state)

private fun qualifierIsBeingResolved(call: Call, state: ResolveState): Boolean =
        if (call is Qualified) {
            call.qualifier().isAncestor(state.get(ElixirPsiImplUtil.ENTRANCE), strict = false)
        } else {
            false
        }
